"""Configuration package for Sultan Assistant."""

from config.settings import Settings, DEFAULT_GEMINI_MODEL, CONVERSATION_HISTORY_LIMIT
from config.prompts import (
    WELCOME_TEXT,
    HELP_TEXT,
    RESET_TEXT,
    UNAUTHORIZED_DENIAL_TEXT,
    FALLBACK_ERROR_TEXT,
    IMAGE_ERROR_TEXT,
    DEFAULT_VISION_PROMPT,
    UNSUPPORTED_MESSAGE_TEXT,
    TRADING_SYSTEM_INSTRUCTIONS,
)

__all__ = [
    "Settings",
    "DEFAULT_GEMINI_MODEL",
    "CONVERSATION_HISTORY_LIMIT",
    "WELCOME_TEXT",
    "HELP_TEXT",
    "RESET_TEXT",
    "UNAUTHORIZED_DENIAL_TEXT",
    "FALLBACK_ERROR_TEXT",
    "IMAGE_ERROR_TEXT",
    "DEFAULT_VISION_PROMPT",
    "UNSUPPORTED_MESSAGE_TEXT",
    "TRADING_SYSTEM_INSTRUCTIONS",
]
