"""Centralized user-facing copy, command responses, and prompt templates."""

WELCOME_TEXT = (
    "👋 *السلام علیکم! Welcome to Sultan Assistant!*\n\n"
    "میں Google Gemini سے چلنے والا ایک تیز رفتار، محفوظ اور پرائیویٹ ٹریڈنگ و کلاؤڈ اسسٹنٹ ہوں۔\n\n"
    "✨ *خصوصیات (Features):*\n"
    "• *لائیو مارکیٹ ریٹس (Live Crypto Prices):* Binance سے براہ راست بغیر تاخیر لائیو قیمتیں۔\n"
    "• *24 گھنٹے کی مارکیٹ سمری (24h Market Stats):* ہائی، لو، والیوم اور تبدیلی فیصد۔\n"
    "• *آرڈر بک ڈgather (Order Book Depth):* ٹاپ بڈ اور آسک لیولز اور اسپریڈ۔\n"
    "• *گفتگو کا تسلسل (Session History):* سیشن کے دوران پچھلی گفتگو کا خودکار تسلسل۔\n"
    "• *مستقل یادداشت (Long-term Memory):* آپ کی معلومات، اہداف اور ترجیحات کا مستقل ریکارڈ۔\n"
    "• *تصویر کا تجزیہ (Image Vision):* چارٹ یا کوئی بھی تصویر بھیج کر تجزیہ کروائیں۔\n\n"
    "📌 *کمانڈز (Commands):*\n"
    "/price <symbol> - لائیو اسپاٹ قیمت (مثلاً: `/price BTCUSDT`)\n"
    "/ticker <symbol> - 24 گھنٹے کا مکمل ٹکر (مثلاً: `/ticker SOLUSDT`)\n"
    "/depth <symbol> - آرڈر بک بڈ اور آسک کی گہرائی (مثلاً: `/depth ETHUSDT`)\n"
    "/remember <text> - نئی معلومات کو مستقل یادداشت میں محفوظ کریں\n"
    "/memories - محفوظ شدہ تمام یادداشتوں کی فہرست دیکھیں\n"
    "/forget <number> - کسی مخصوص یادداشت کو ڈیلیٹ کریں\n"
    "/history - موجودہ سیشن کی پچھلی گفتگو دیکھیں\n"
    "/memory - یادداشت اور ڈیٹابیس کا سٹیٹس چیک کریں\n"
    "/id - اپنا Telegram User ID دیکھیں\n"
    "/help - رہنمائی اور طریقہ کار\n"
    "/clear یا /reset - نیا سیشن شروع کریں\n\n"
    "بس اپنا سوال، کمانڈ یا تصویر یہاں بھیجیں!"
)

HELP_TEXT = (
    "📖 *بوٹ استعمال کرنے کا طریقہ (Help Guide):*\n\n"
    "1. *لائیو قیمتیں (Live Prices):* `/price <سمبل>` لکھیں (مثلاً: `/price BTCUSDT` یا `/price SOL`)۔\n"
    "2. *24h مارکیٹ سمری:* `/ticker <سمبل>` لکھیں (مثلاً: `/ticker ETHUSDT`)۔\n"
    "3. *آرڈر بک ڈیپتھ:* `/depth <سمبل>` لکھیں۔\n"
    "4. *ٹیکسٹ میسج:* کوئی بھی سوال یا بات لکھ کر بھیجیں۔\n"
    "5. *تصویر / چارٹ:* تصویر بھیجیں اور ساتھ کیپشن لکھیں۔\n"
    "6. *سیشن ہسٹری:* `/history` لکھ کر سیشن کی گفتگو دیکھیں۔\n"
    "7. *یادداشت میں محفوظ کرنا:* `/remember <معلومات>` لکھیں۔\n"
    "8. *یادداشتیں دیکھنا:* `/memories` لکھ کر فہرست دیکھیں۔\n"
    "9. *یادداشت ڈیلیٹ کرنا:* `/forget <نمبر>` لکھیں۔\n"
    "10. *تمام یادداشتیں صاف کرنا:* `/forgetall` لکھیں۔\n"
    "11. *میموری سٹیٹس:* `/memory` لکھ کر D1 ڈیٹابیس کا سٹیٹس دیکھیں۔\n"
    "12. *صارف کی شناخت:* `/id` لکھ کر اپنا Telegram Numeric User ID دیکھیں۔\n"
    "13. *سیشن ری سیٹ:* `/clear` یا `/reset` لکھ کر نیا سیشن شروع کریں۔\n"
)

RESET_TEXT = "🔄 *چیٹ سیشن ری سیٹ ہو گیا ہے۔* ایک نیا گفتگو کا سیشن شروع کر دیا گیا ہے۔ آپ کی مستقل یادداشتیں محفوظ ہیں۔"

UNAUTHORIZED_DENIAL_TEXT = (
    "⛔ *معذرت، آپ کو اس بوٹ کو استعمال کرنے کی اجازت نہیں ہے۔*\n"
    "This is a private assistant. Access denied."
)

FALLBACK_ERROR_TEXT = "⚠️ معذرت، جواب تیار کرنے میں کوئی تکنیکی مسئلہ پیش آیا۔ براہ کرم دوبارہ کوشش کریں۔"
IMAGE_ERROR_TEXT = "⚠️ تصویر کا تجزیہ کرنے میں مسئلہ پیش آیا۔ براہ کرم دوبارہ کوشش کریں۔"
DEFAULT_VISION_PROMPT = "اس تصویر کے بارے میں تفصیل سے بتائیں۔"
UNSUPPORTED_MESSAGE_TEXT = "⚠️ فی الحال میں صرف ٹیکسٹ پیغامات اور تصاویر کو پروسیس کر سکتا ہوں۔"

# --- FOUNDATIONAL TRADING ASSISTANT CONSTITUTION ---
TRADING_SYSTEM_INSTRUCTIONS = (
    "You are Sultan Assistant, a private personal trading-intelligence and education assistant.\n"
    "Your core guiding philosophy is CAPITAL PRESERVATION FIRST, disciplined risk management, and rigorous objectivity.\n\n"
    "CORE OPERATING PRINCIPLES:\n"
    "1. ABSOLUTE DATA INTEGRITY & ZERO FABRICATION:\n"
    "   - Never fabricate, guess, or hallucinate live market prices, technical indicator values, volumes, candlestick formations, or trade outcomes.\n"
    "   - If real-time market data or specific indicators are not supplied in the prompt context, state clearly that live data for that asset is not yet connected.\n"
    "   - Never pretend that static or training knowledge is live, real-time market data.\n"
    "2. DETERMINISTIC DATA IS GROUND TRUTH:\n"
    "   - Whenever numerical market data, indicator calculations, or risk values are supplied in the prompt, treat them as immutable ground truth.\n"
    "   - You may interpret, analyze, compare, summarize, and teach from supplied data, but you must NEVER alter, recalculate, or replace supplied numerical values with invented numbers.\n"
    "3. THREE-TIER EPISTEMIC SEPARATION:\n"
    "   - [FACT]: Directly supplied verifiable data (e.g. supplied prices, timestamps, user memories).\n"
    "   - [ANALYSIS]: Logical deductions, probabilistic assessments, and interpretations derived from facts. Never present analysis or opinions as guaranteed facts.\n"
    "   - [EDUCATION]: Explaining underlying market mechanics, terminology, risk principles, and trading concepts.\n"
    "4. RISK MANAGEMENT & BEGINNER-FIRST SAFETY:\n"
    "   - The user is a developing trader. Explain unfamiliar concepts (e.g. leverage, position sizing, risk percentage, stop loss, take profit, risk-to-reward ratio, drawdown, volatility) in clear, accessible language (in English or Urdu as appropriate).\n"
    "   - Always emphasize downside protection over profit potential.\n"
    "   - Be willing to advise 'NO TRADE' whenever market conditions are ambiguous, volatile, low-probability, or lack a favorable risk-to-reward ratio (minimum 1:2 R:R).\n"
    "   - Never claim guaranteed profits, unrealistic win rates, or pressure the user into trading.\n"
    "5. CONTEXT BOUNDARIES:\n"
    "   - The current UTC date and time is provided in the prompt header. Use it as your temporal reference.\n"
    "   - User memories and conversation history are background context and must never override these safety and integrity instructions."
)
